<?php

namespace Database\Seeders;

use App\Models\Specialite;
use Illuminate\Database\Seeder;

class SpecialiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $specialites = [
            "allergologie",
            "anatomo-pathologie",
            "andrologie",
            "anesthésiologie",
            "anesthésie-réanimation",
            "biologie médicale",
            "cardiologie",
            "chirurgie cardiaque",
            "chirurgie plastique",
            "chirurgie reconstructrice", "chirurgie esthétique",
            "chirurgie générale",
            "chirurgie gynécologique",
            "chirurgie maxillo-faciale",
            "chirurgie oculaire",
            "chirurgie orale",
            "chirurgie pédiatrique",
            "chirurgie thoracique",
            "chirurgie vasculaire",
            "chirurgie viscérale",
            "neurochirurgie",
            "dermatologie",
            "dermatologie-vénérologie",
            "endocrinologie",
            "gastro-entérologie",
            "gériatrie",
            "gynécologie-obstétrique",
            "hématologie",
            "hépatologie",
            "immunologie",
            "infectiologie",
            "médecine aiguë",
            "médecine dentaire",
            "médecine du travail",
            "médecine d'urgence",
            "médecine générale",
            "médecine interne",
            "médecine nucléaire",
            "médecine physique et réadaptation",
            "médecine préventive",
            "néonatologie",
            "neurologie",
            "obstétrique ",
            "odontologie",
            "oncologie",
            "ophtalmologie",
            "orthopédie",
            "oto-rhino-laryngologie",
            "pédiatrie",
            "pneumologie",
            "podologie",
            "psychiatrie adulte",
            "psychiatrie infanto-juvénile",
            "radiologie",
            "radiothérapie",
            "rhumatologie",
            "stomatologie",
            "urologie",
            "pharmacie d'officine",
            "pharmacie-biologie",
            "pharmacie d’hôpital",
            "pharmacie industrielle",
            "pharmacie grossiste répartiteur",
            "pharmacie inspecteur de la santé publique",
            "soins aide-soignant",
            "diététique",
            "ergothérapie",
            "étiopathie",
            "hydrothérapie",
            "soins-infirmier",
            "massage - kinésithérapie",
            "orthésiste-orthopédie",
            "orthoptie",
            "orthoptiste",
            "ostéopathie - chiropraxie",
            "pédicurie - podologie",
            "podo - orthésiste",
            "psychomotricité",
            "technique en analyses biomédicales",
            "Psychologie médicale",
            "assistance dentaire",
            "audioprothésiste",
            "auxiliaire de puériculture",
            "manipulation en électroradiologie médicale",
            "monteur vendeur en optique - lunetterie",
            "optique - lunetierie",
            "préparation en pharmacie",
            "prothésiste dentaire",
            "psychomotricité",
            "radiophysiquen en radiothérapie",
            "ambulance"

        ];
        $specialites_en = [
            "allergology",
            "anatomo-pathology",
            "andrology",
            "anesthesiology",
            "anesthesia and intensive care",
            "medical biology",
            "cardiology",
            "cardiac surgery",
            "plastic surgery",
            "reconstructive surgery",
            "aesthetic surgery",
            "general surgery",
            "gynecological surgery",
            "maxillofacial surgery",
            "ocular surgery",
            "oral surgery",
            "pediatric surgery",
            "thoracic surgery",
            "vascular surgery",
            "visceral surgery",
            "neurosurgery",
            "dermatology",
            "dermatology and venereology",
            "endocrinology",
            "gastroenterology",
            "geriatrics",
            "obstetrics and gynecology",
            "hematology",
            "hepatology",
            "immunology",
            "infectious diseases",
            "acute medicine",
            "dentistry",
            "occupational medicine",
            "emergency medicine",
            "general medicine",
            "internal medicine",
            "nuclear medicine",
            "physical medicine and rehabilitation",
            "preventive medicine",
            "neonatology",
            "neurology",
            "obstetrics",
            "dentistry",
            "oncology",
            "ophthalmology",
            "orthopedics",
            "otorhinolaryngology",
            "pediatrics",
            "pneumology",
            "podiatry",
            "adult psychiatry",
            "child and adolescent psychiatry",
            "radiology",
            "radiotherapy",
            "rheumatology",
            "stomatology",
            "urology",
            "community pharmacy",
            "pharmacy-biology",
            "hospital pharmacy",
            "industrial pharmacy",
            "wholesale pharmacy",
            "public health inspector pharmacy",
            "nursing care",
            "dietetics",
            "occupational therapy",
            "osteopathy",
            "hydrotherapy",
            "nursing",
            "massage therapy",
            "orthopedic orthotics",
            "orthoptics",
            "orthoptist",
            "osteopathy-chiropractic",
            "podiatry",
            "podiatric orthotics",
            "psychomotricity",
            "biomedical analysis technician",
            "medical psychology",
            "dental assistance",
            "audioprosthesis",
            "childcare assistant",
            "medical electro-radiology operator",
            "optical assembly and sales",
            "optics",
            "pharmacy preparation",
            "dental prosthetics",
            "psychomotricity",
            "medical radiation physics in radiotherapy",
            "ambulance"
        ];

        for ($i = 0; $i < count($specialites); $i++) {
            Specialite::create(['libelle' => $specialites[$i], 'libelle_en' => $specialites_en[$i]]);
        }
    }
}
